from typing  import Protocol
from models.User import User
from models.graph.GraphEdgesSettings import GraphEdgeSettings

class IAdminSecretDitoRepo(Protocol):
    async def GetAllUsers(self) -> list[User]: ...
    async def GetInvalidEdges(self) -> list[GraphEdgeSettings]: ...
    async def SaveAssignationsToTxt(self, assignations: list[tuple[User, User]], filename: str = "assignations.txt") -> None:
        ...

class ISecretDitoRepo(Protocol):
    async def GetUserById(self, user_id: int) -> User: ...
    async def CreateUser(self, user: User): ...
    async def UpdateUser(self, user: User): ...
